spring.application.name=school
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/hogwarts
spring.datasource.username=student
spring.datasource.password=chocolatefrog
spring.jpa.hibernate.ddl-auto = validate
spring.jpa.hibernate.ddl=create

spring.liquibase.change-log=classpath:liquibase/db/changelog/lesson-three.yaml
